var categories = ["red", "blue", "green", "round", "electronic","automotive","square","yellow","orange","purple"]
var randomnumber = Math.floor(Math.random() * categories.length);
function setupGame() {
    $('#headtitle').html("Spy on something <b><u><i>" + categories[randomnumber] + "</i></u></b>");

    $('#topimage').attr('src', 'imgABC/clickhere.jpg');
    for (var ii = 0; ii < 26; ii++) {
        $('#pic' + ii).attr('src', 'imgABC/white.jpg');
    }
    $('#pictable').hide();
    $('#seeFinals').hide();
    $('#seeAllpics').hide();
    $('#restart').hide();
    $('#endGame').hide();
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// when called, this function shows all the pictures that have been taking during the game session
function showfound() {
    var imgSrc;
    for (var i = 0; i < 26; i++) {
        imgSrc = $('#pic' + i).attr("src");
        console.log(imgSrc);
        if (imgSrc == "imgABC/white.jpg") {
            $('#pic' + i).hide();
        } else {
            $('#pic' + i).show();
        }
    }
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// adds score to total score
var score = 0;
function addScore() {
    score = score + 1;
    $('#score').html('Score: ' + score);
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// finds which cell has the class 'activeTarget' which is then used to put the picture in the correct cell
function getActiveTarget() {
    //find which cell has the class active target
    var blah = $('.activeTarget').first();
    return blah
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// gets the location using HTML5 geolocation. This will be stored in Parse
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    }
    else { alert("Geolocation is not supported by this browser."); }
}
var lat;
var longi;
function showPosition(position) {
    lat = position.coords.latitude;
    longi = position.coords.longitude;
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This function is the way I store things to Parse. The first half of the function makes a call using the imgur api
// and returns the url generated by the website. I generated this code by looking through the imgur and parse documentation
var uploadcount = 0;
function upload(myfile) {
    var reader = new FileReader();
    reader.onload = function (event) {
        object = {};
        object.filename = myfile.name;
        object.data = event.target.result;
        object.data = object.data.slice(object.data.indexOf('base64') + 7, object.data.length)
        $.ajax({
            url: 'https://api.imgur.com/3/image',
            method: 'POST',
            headers: {
                Authorization: 'Client-ID 1b29a07068ab56c',
            },
            data: {
                image: object.data,
                type: 'base64'
            },
/////////////////////////////////////////////////////////////////////////////////////////
// this half of the function only executes when the first half is successful. It makes 
// a call to Parse and stores the location, the category being spied on, and the imgur
// url of the picture that was taken. When it finishes storing the picture, it puts it
// in the main box for a few seconds and then the user moves on to the next category
            success: function (obj, stat, xhr) {
                var upIMG = Parse.Object.extend("specific");
                var upimg = new upIMG();
                upimg.set("urlPath", JSON.parse(xhr.responseText).data.link);
                upimg.set("latitude", lat);
                upimg.set("longitude", longi);
                upimg.set("category", categories[randomnumber]);
                upimg.save(null, {
                    success: function () {
                        $('#pic' + uploadcount).attr('src', JSON.parse(xhr.responseText).data.link);
                        uploadcount++;
                    }
                });
            }
        });
    };
    reader.readAsDataURL(myfile)

}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// this is the timer that is set for 2 minutes and goes into "endgame" mode when the timer runs out
var go = false;
var seconds = 120;
var countdownTimer = setInterval('secondPassed()', 1000);
function secondPassed() {
    if (go) {
        var minutes = Math.round((seconds - 30) / 60);
        var remainingSeconds = seconds % 60;
        if (remainingSeconds < 10) {
            remainingSeconds = "0" + remainingSeconds;
        }
        document.getElementById('timer').innerHTML = minutes + ":" + remainingSeconds;
        if (seconds == 0) {
            clearInterval(countdownTimer);
            $('#seeFinals').show();
            $('#seeAllpics').show();
            $('#inputtop').hide();
            $('#restart').show();
            $('#endGame').hide();

        } else {
            seconds--;
        }
    }
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////DOCUMENT.READY PART//////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
$(document).ready(function () {

    Parse.initialize("TohTpNrTgJf0MTUkm5Ax9LtzfXoyaEOmSaQKnGRl", "p7CQveFxWDaYln4pNawiV8qkXiRuda9iR3zBqw8v");
    $('#submit').hide();

    $('#score').html('Score: ' + score);
    var imagepath;
//////////////////////////////////////////////////////////////////////////////////////////////////
// runs when the user finds a picture. it removes the class from all the cells and adds the class
// to the clicked cell
    $(".spyTargetFin").click(function (event) { // triggers open file menu
        for (var jj = 0; jj < 26; jj++) {
            $('#pic' + jj).removeClass('activeTarget');
        }
        $(this).addClass("activeTarget");
        $('#takePicture').trigger('click');
        return false;
    });
// calls the function that opens the camera on the phone and puts the picture taken in the right cell
    $('#takePicture').on('change', function (e) {
        e.preventDefault();
        if (this.files.length === 0) return;
        var imageFile = this.files[0];
        imagepath = imageFile;
        getLocation();
        setTimeout(function () {
            upload(imagepath);
            addScore();
            $('#topimage').attr('src', 'imgABC/clickhere.jpg');
            }, 1500);
        var activeTarget = getActiveTarget();
        var imgURL = URL.createObjectURL(imageFile);
        activeTarget.attr('src', imgURL);
        activeTarget.removeClass('activeTarget');
    });
//////////////////////////////////////////////////////////////////////////////////////////////////

    $('body').hide().fadeIn(1000);
    setupGame();
// starts the game by hiding stuff and showing other things
    $('#getstarted').click(function () {
        go = true;
        $('#getstarted').hide();
        $('#pictable').show();
        for (var pp = 0; pp < 26; pp++) {
            $('#pic' + pp).hide();
        }
        $('#headtop').hide();
        $('#endGame').show();
    });



//////////////////////////////////////////////////////////////////////////////////////////////////
// does stuff when the game is done
    $('#seeFinals').click(function () {
       showfound();
    });
    $('#seeAllpics').click(function () {
        window.location.href = "htmlspecificEnd.html"
    });
    $('#restart').click(function () {
        window.location.href = "htmlspecific.html"
    });

    $('#endGame').click(function () {
        seconds = 0;
    });

    $('#skip').click(function () {
        randomnumber = Math.floor(Math.random() * categories.length);
        $('#headtitle').html("Now spy on something <b><u><i>" + categories[randomnumber] + "</i></u></b>");
        //        score--;
    });
});


//setTimeout(function () { $('#pic0').attr('src', 'img/white.jpg'); }, 1000);